"""Configuration package for Rankle"""

from .patterns import COMMON_SUBDOMAINS
from .settings import (
    CDN_DETECTION_THRESHOLD,
    CRT_SH_TIMEOUT,
    CRT_SH_URL,
    DEFAULT_HEADERS,
    DEFAULT_TIMEOUT,
    DNS_NAMESERVERS,
    DNS_TIMEOUT,
    GEO_API_TIMEOUT,
    MAX_BODY_SIZE,
    MAX_CONCURRENT_REQUESTS,
    MAX_DISPLAY_ITEMS,
    MAX_DISPLAY_ORIGINS,
    MAX_DISPLAY_SUBDOMAINS,
    MAX_DISPLAY_TECHS,
    MAX_REDIRECTS,
    MAX_RESPONSE_TIME_SAMPLES,
    MAX_RETRY_WAIT_SECONDS,
    MAX_SUBDOMAINS,
    MINIMUM_DETECTION_CONFIDENCE,
    RATE_LIMIT_DELAY,
    RATE_LIMIT_DIMINISHING_FACTOR,
    SSL_TIMEOUT,
    SSL_VERIFY,
    USER_AGENT,
    WAF_ACTIVE_DETECTION,
    WAF_DETECTION_THRESHOLD,
    WAF_MAX_PAYLOADS,
    WHOIS_TIMEOUT,
)


__all__ = [
    # Detection thresholds
    "CDN_DETECTION_THRESHOLD",
    "MINIMUM_DETECTION_CONFIDENCE",
    "WAF_DETECTION_THRESHOLD",
    # Display limits
    "MAX_DISPLAY_ITEMS",
    "MAX_DISPLAY_ORIGINS",
    "MAX_DISPLAY_SUBDOMAINS",
    "MAX_DISPLAY_TECHS",
    # HTTP settings
    "DEFAULT_HEADERS",
    "DEFAULT_TIMEOUT",
    "MAX_BODY_SIZE",
    "MAX_REDIRECTS",
    "USER_AGENT",
    # DNS settings
    "DNS_NAMESERVERS",
    "DNS_TIMEOUT",
    # SSL/TLS settings
    "SSL_TIMEOUT",
    "SSL_VERIFY",
    # Certificate Transparency
    "CRT_SH_TIMEOUT",
    "CRT_SH_URL",
    "MAX_SUBDOMAINS",
    # Rate limiting
    "MAX_CONCURRENT_REQUESTS",
    "MAX_RESPONSE_TIME_SAMPLES",
    "MAX_RETRY_WAIT_SECONDS",
    "RATE_LIMIT_DELAY",
    "RATE_LIMIT_DIMINISHING_FACTOR",
    # WAF detection
    "WAF_ACTIVE_DETECTION",
    "WAF_MAX_PAYLOADS",
    # API timeouts
    "GEO_API_TIMEOUT",
    "WHOIS_TIMEOUT",
    # Patterns
    "COMMON_SUBDOMAINS",
]
